---
title: "Assignment 8"
author: "David Goldsmith"
date: "2023-01-26"
output: html_document
---

## Code Reflection
1. Go through your recent assignments and the posted solutions (Assignment 6 posted solutions and Weekly Assignment 2 solutions) - compare your code to the posted code.
* Can you run your simulated data function with new values for the means? If not, what do you need to change about your code?

#### Yes! but the second function needed to modified

* Are there differences between the posted code and yours? Did you notice you were missing anything?

#### In the weekly assignment, code could be reproduced if means were changed throughout

* Make sure you annotate your code using # and leave brief descriptions of your thought process.

## Code annotation
2. I used dryad data to reconstruct a publication-quality figure. Copy my code into an Rmd file and annotate what each ggplot line of code is doing, including any arguments. You can use a combination of googling and ‘trial/error coding:’ change the arguments/options to visually see how it affects the plot.

```{r}
## Set up libraries
library(tidyverse)
library(ggthemes)


# Data obtained from Veysey Powell and Babbitt 2016: An experimental test of buffer utility as a technique for managing pool-breeding amphibians https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.547rp

dryadData <- read.table("Data/veysey-babbitt_data_amphibians.csv", header=TRUE, sep=",", stringsAsFactors = TRUE) #reads and saves the csv

# glimpse(dryadData)
# head(dryadData)
# table(dryadData$species)

dryadData$species<-factor(dryadData$species, labels=c("Spotted Salamander", "Wood Frog")) #creating 'labels' to use for the plot

#class(dryadData$treatment) #used to make sure next command "factor()" would work on dryadData$treatment 
dryadData$treatment <- factor(dryadData$treatment, 
            levels=c("Reference",
                     "100m", "30m")) #set treatment into 3 categories


p<- ggplot(data=dryadData, #loads the data
       aes(x=interaction(wetland, treatment), 
           y=count.total.adults, fill=factor(year)))  +  geom_bar(position="dodge", stat="identity", color="black") + #groups wetland and treatment. y= makes y about column "count.total.adults". geom_bar sets graph as a bar graph, position dodge sets bars next to one another, stat="identity" tells it to skip the aggregation and that you'll provide the y values. fill= tells it to divide scale and treatments by year
  ylab("Number of breeding adults") + #gives the y axis label
  xlab("") + #gives the x axis label
  scale_y_continuous(breaks = c(0,100,200,300,400,500)) + # gives y axis scale
  scale_x_discrete(labels=c("30 (Ref)", "124 (Ref)", "141 (Ref)", "25 (100m)","39 (100m)","55 (100m)","129 (100m)", "7 (30m)","19 (30m)","20 (30m)","59 (30m)")) + #like the y scale, but because it is categorical and not continuous, labels tells us what to label each bar on the x-axis
  facet_wrap(~species, nrow=2, strip.position="right") + #
  theme_few() + scale_fill_grey() + #theme of graph and fill color by a grayscale
  theme(panel.background = element_rect(fill = 'gray94', color = 'black'), legend.position="top", legend.title= element_blank(), axis.title.y = element_text(size=12, face="bold", colour = "black"), strip.text.y = element_text(size = 10, face="bold", colour = "black")) + #modifies theme further. panel background modifies as described. fill tells us fill color of background, color gives color of outline lines. legend stuff describes the design of the legend, placing it on top and not giving it a label. axis titles describe design of axis labels (left side). strip text describes design of y axis graph labels (right side).
  guides(fill=guide_legend(nrow=1,byrow=TRUE)) 

p
```

